

***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 19, in <module>
    widgetHolder.get_widget_list()[1][3].invoke()
  File "E:\python\Python27\Lib\lib-tk\Tkinter.py", line 2202, in invoke
    return self.tk.call(self._w, 'invoke')
TclError: invalid command name ".38712904L"

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 20, in <module>
    widgetHolder.get_widget_list()[1][3].invoke()
  File "E:\python\Python27\Lib\lib-tk\Tkinter.py", line 2202, in invoke
    return self.tk.call(self._w, 'invoke')
TclError: invalid command name ".39250056L"

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 42, in create_second_row
    self.label_01_04.pack()
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2143, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside . which already has slaves managed by grid

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 42, in create_second_row
    self.label_01_04.pack_configure()
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2143, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside . which already has slaves managed by grid

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 42, in create_second_row
    self.label_01_04.pack()
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2143, in pack_configure
    + self._options(cnf, kw))
_tkinter.TclError: cannot use geometry manager pack inside . which already has slaves managed by grid

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 18, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 44, in create_second_row
    self.label_01_04 = ttk.Button(self.master, text="Add", name="Add")
  File "E:\python\Python371\lib\tkinter\ttk.py", line 614, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "E:\python\Python371\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: window name starts with an upper-case letter: "Add"

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 18, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 44, in create_second_row
    self.label_01_04 = ttk.Button(self.master, name="Add")
  File "E:\python\Python371\lib\tkinter\ttk.py", line 614, in __init__
    Widget.__init__(self, master, "ttk::button", kw)
  File "E:\python\Python371\lib\tkinter\ttk.py", line 559, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2299, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: window name starts with an upper-case letter: "Add"

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 18, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 52, in create_second_row
    self.label_01_04.invoke(self.add_line_of_data_01())
TypeError: add_line_of_data_01() missing 2 required positional arguments: 'func' and 'event'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 18, in __init__
    self.create_second_row()
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 56, in create_second_row
    print(blalbabla.widget.__class__)
AttributeError: '_tkinter.Tcl_Obj' object has no attribute 'widget'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder()
TypeError: __init__() missing 1 required positional argument: 'master'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 22, in <module>
    root.doonneevent()
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'doonneevent'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 21, in <module>
    print(widgetHolder.get_widget_list()[1][0].get())
AttributeError: 'Label' object has no attribute 'get'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 21, in <module>
    print(widgetHolder.get_widget_list()[1][0].cget())
TypeError: cget() missing 1 required positional argument: 'key'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 21, in <module>
    print(widgetHolder.get_widget_list()[1][0].cget())
TypeError: cget() missing 1 required positional argument: 'key'

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    if len(self.widgetList) == 0:
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    if len(self.widgetList) == 0:
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 16, in <module>
    widgetHolder = WidgetHolder(root)
  File "E:\python\projects\create_text_file_through_the_menu\app\widget_holder.py", line 14, in __init__
    if self.widgetList:
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  File "E:\python\Python371\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
  [Previous line repeated 495 more times]
RecursionError: maximum recursion depth exceeded

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 20, in <module>
    widgetHolder.get_widget_list()[1][1].insert(0,"blablabla")
TypeError: 'list' object is not callable

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 20, in <module>
    widgetHolder.get_widget_list()
TypeError: 'list' object is not callable

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 21, in <module>
    widgetHolder.get_widget_list()[1][1].insert(0,"blablabla")
TypeError: 'list' object is not callable

***********************************************



***********************************************
Traceback (most recent call last):
  File "E:/python/projects/create_text_file_through_the_menu/app/create_text_file_throug_the_menu_main_01.py", line 20, in <module>
    print(widgetHolder.get_widget_list())
TypeError: 'list' object is not callable

***********************************************

